apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sdlbot-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: do-block-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdlbot-deployment
  labels:
    app: sdlbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdlbot
  template:
    metadata:
      labels:
        app: sdlbot
    spec:
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: sdlbot-pvc
      containers:
      - name: sdlbot
        image: mgalgs/sdlbot:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/data"
          name: storage-volume
        command: ["python"]
        args: ["/usr/src/app/main.py"]
        env:
        - name: "STORAGE_DIR"
          value: "/data"
        - name: "CLIENT_ID"
          valueFrom:
            secretKeyRef:
              name: "sdlbot-secrets"
              key: "CLIENT_ID"
        - name: "CLIENT_SECRET"
          valueFrom:
            secretKeyRef:
              name: "sdlbot-secrets"
              key: "CLIENT_SECRET"
        - name: "REDDIT_USERNAME"
          valueFrom:
            secretKeyRef:
              name: "sdlbot-secrets"
              key: "REDDIT_USERNAME"
        - name: "REDDIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: "sdlbot-secrets"
              key: "REDDIT_PASSWORD"
        - name: "PROD"
          value: "yes"
